package com.orange.project.entity;

import java.util.Date;

public class ProductType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.names
     *
     * @mbggenerated
     */
    private String names;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.remake
     *
     * @mbggenerated
     */
    private String remake;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.merchant_no
     *
     * @mbggenerated
     */
    private String merchantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.id
     *
     * @return the value of product_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.id
     *
     * @param id the value for product_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.names
     *
     * @return the value of product_type.names
     *
     * @mbggenerated
     */
    public String getNames() {
        return names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.names
     *
     * @param names the value for product_type.names
     *
     * @mbggenerated
     */
    public void setNames(String names) {
        this.names = names == null ? null : names.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.remake
     *
     * @return the value of product_type.remake
     *
     * @mbggenerated
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.remake
     *
     * @param remake the value for product_type.remake
     *
     * @mbggenerated
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.merchant_no
     *
     * @return the value of product_type.merchant_no
     *
     * @mbggenerated
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.merchant_no
     *
     * @param merchantNo the value for product_type.merchant_no
     *
     * @mbggenerated
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo == null ? null : merchantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.created_by
     *
     * @return the value of product_type.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.created_by
     *
     * @param createdBy the value for product_type.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.created_time
     *
     * @return the value of product_type.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.created_time
     *
     * @param createdTime the value for product_type.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.updated_by
     *
     * @return the value of product_type.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.updated_by
     *
     * @param updatedBy the value for product_type.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.updated_time
     *
     * @return the value of product_type.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.updated_time
     *
     * @param updatedTime the value for product_type.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}