server:
  port: 8066
spring:
  http:
  encoding:
    force: true
    charset: utf-8
    enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #数据源
  jpa:
    database: mysql
    show-sql: true

  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:TIELU
    url: jdbc:mysql://127.0.0.1:3306/frame?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

  servlet:
    #文件上传
    multipart:
      max-file-size: 5MB      #限制单个文件的最大值
      max-request-size: 10MB  #限制上传的多个文件的总大小
      location: D:\\fileUpload
  resources:
    static-locations: classpath:/static/, file:${spring.servlet.multipart.location}
  #  默认配置
  freemarker:
    # 设置模板后缀名
    suffix: .html
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    settings:
      template_update_delay: 0
    # 设置ftl文件路径，默认是/templates，
    template-loader-path: classpath:/templates


#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true        #  使用驼峰转换
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.orange.project.entity      #  实体类包位置
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

#mybatis分页配置
pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

#自定义属性
custom:
  #markdown文件存放地址
  markdown: D:\md

ConfigSourceMethod: database

ConfigSourceClass: com.orange.project.controller.MerchantParaFromDB

