package com.orange.project.mapper;

import com.orange.project.entity.SysLayout;

import java.util.List;

public interface SysLayoutMapper {

    List<SysLayout> selectAllByMerchantNo(String merchantNo);

//    List<SysLayout> selectAll(SysLayout sysLayout);

    List<SysLayout> selectAll(SysLayout sysLayout);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    int insert(SysLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    int insertSelective(SysLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    SysLayout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysLayout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_layout
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysLayout record);
}